apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-etudiant-service
  labels:
    app: faculty-etudiant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-etudiant-service
  template:
    metadata:
      labels:
        app: faculty-etudiant-service
    spec:
      containers:
        - name: faculty-etudiant-service
          image: faculty_management-faculty-etudiant-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_SERVICE_URL
              value: "http://faculty-config-service:9999"
            - name: DISCOVERY_SERVICE_URL
              value: "http://faculty-discovery-service:8761/eureka"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://faculty-mysql-service:3306/ex3_etudiant?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: faculty-etudiant-service
spec:
  type: ClusterIP
  selector:
    app: faculty-etudiant-service
  ports:
    - port: 8082
      targetPort: 8082
